name: Marvel Continuous Integration

on: [push, pull_request]

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run lint
        run: npx run lint
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
